# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.10.1


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(455, 401)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 60, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_search0 = QtWidgets.QPushButton(Dialog)
        self.pushButton_search0.setGeometry(QtCore.QRect(80, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_search0.setFont(font)
        self.pushButton_search0.setObjectName("pushButton_search0")
        self.pushButton_cancel0 = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel0.setGeometry(QtCore.QRect(250, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancel0.setFont(font)
        self.pushButton_cancel0.setObjectName("pushButton_cancel0")
        self.lineEdit_website0 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_website0.setGeometry(QtCore.QRect(90, 100, 331, 31))
        self.lineEdit_website0.setObjectName("lineEdit_website0")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 103, 50, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 236, 50, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_website1 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_website1.setGeometry(QtCore.QRect(90, 233, 331, 31))
        self.lineEdit_website1.setObjectName("lineEdit_website1")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 190, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_search1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_search1.setGeometry(QtCore.QRect(80, 323, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_search1.setFont(font)
        self.pushButton_search1.setObjectName("pushButton_search1")
        self.pushButton_cancel1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel1.setGeometry(QtCore.QRect(250, 323, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_cancel1.setFont(font)
        self.pushButton_cancel1.setObjectName("pushButton_cancel1")
        self.lineEdit_username = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_username.setGeometry(QtCore.QRect(90, 270, 331, 31))
        self.lineEdit_username.setObjectName("lineEdit_username")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 273, 50, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_website0, self.pushButton_search0)
        Dialog.setTabOrder(self.pushButton_search0, self.pushButton_cancel0)
        Dialog.setTabOrder(self.pushButton_cancel0, self.lineEdit_website1)
        Dialog.setTabOrder(self.lineEdit_website1, self.lineEdit_username)
        Dialog.setTabOrder(self.lineEdit_username, self.pushButton_search1)
        Dialog.setTabOrder(self.pushButton_search1, self.pushButton_cancel1)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "密码通v1.0.0  查询服务"))
        self.label.setText(_translate("Dialog", "请输入网址，查询账号和密码："))
        self.pushButton_search0.setText(_translate("Dialog", "查询"))
        self.pushButton_cancel0.setText(_translate("Dialog", "取消"))
        self.label_2.setText(_translate("Dialog", "网址："))
        self.label_3.setText(_translate("Dialog", "网址："))
        self.label_4.setText(_translate("Dialog", "请输入网址、账号，查询账号和密码："))
        self.pushButton_search1.setText(_translate("Dialog", "查询"))
        self.pushButton_cancel1.setText(_translate("Dialog", "取消"))
        self.label_5.setText(_translate("Dialog", "账号："))
        self.label_6.setText(_translate("Dialog", "查询系统"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

